name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Install Ninja
        run: |
          sudo apt update
          sudo apt install -y ninja-build

      - name: Configure CMake
        run: |
          cmake -S src -B build-ninja -G Ninja

      - name: Build
        run: |
          cmake --build build-ninja

      - name: Run Tests
        run: |
          ctest --test-dir build-ninja --output-on-failure

      - name: Check Formatting
        run: |
          find src -type f \( -name "*.cpp" -o -name "*.hpp" \) \
            | xargs clang-format --dry-run --Werror