name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install clang-format-15
        run: |
          sudo apt update
          sudo apt install -y clang-format-15

      - name: Install clang-tidy
        run: |
          sudo apt install -y clang-tidy

      - name: Install Ninja
        run: |
          sudo apt update
          sudo apt install -y ninja-build

      - name: Configure CMake
        run: |
          cmake -S src -B build-ninja -G Ninja

      - name: Build
        run: |
          cmake --build build-ninja

      - name: Run clang-tidy
        continue-on-error: true
        run: |
          find src \
            -path "src/third_party" -prune \
            -o \( -name "*.cpp" \) \
            -print \
          | xargs clang-tidy \
              -p build-ninja

      - name: Run Tests
        run: |
          ctest --test-dir build-ninja --output-on-failure

      - name: Check Formatting
        run: |
          find src \
            -path "src/third_party" -prune \
            -o \( -name "*.cpp" -o -name "*.hpp" \) \
            -print \
          | xargs clang-format-15 --dry-run --Werror